#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.21.5
NumPy Configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
Supported SIMD ex

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.array([1, 2, 3, 4, 5])
memory_size = arr.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 20 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vect = np.zeros(10)
null_vect[4] = 1

null_vect

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vect=np.arange(10, 50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
vect=np.array([1,2,3,4,5])
fliped_vect=np.flip(vect)
fliped_vect

array([5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
matrix = np.arange(9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
identity_matrix = np.array([[1 if i == j else 0 for j in range(3)] for i in range(3)])
print(f"3x3 Identity Matrix:\n{identity_matrix}")

3x3 Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
identity_matrix = np.eye(3)
print(f"3x3 Identity Matrix:\n{identity_matrix}")

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
rand_arr = np.random.random((3, 3, 3))
rand_arr

array([[[0.86139866, 0.39663547, 0.63658314],
        [0.30973877, 0.86789451, 0.00427816],
        [0.32610009, 0.94763517, 0.28449689]],

       [[0.26755291, 0.14962029, 0.13976058],
        [0.69509239, 0.05809031, 0.2830756 ],
        [0.07240693, 0.96347041, 0.0623857 ]],

       [[0.12070208, 0.69790219, 0.96299109],
        [0.135522  , 0.19542699, 0.03887292],
        [0.09977199, 0.90869784, 0.67259546]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
arr=np.random.random((10,10))
min_value=np.min(arr)
max_value=np.max(arr)
print(f"10x10 Array with Random Values:\n{arr}")
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

10x10 Array with Random Values:
[[0.28863465 0.87818419 0.42503289 0.39848958 0.36920943 0.99639412
  0.83701251 0.58741911 0.555665   0.51670818]
 [0.4670094  0.42897882 0.66630136 0.70724032 0.90645628 0.29904132
  0.80726737 0.1862843  0.16066592 0.16663117]
 [0.72387915 0.9630001  0.32122871 0.24755283 0.19196133 0.03238721
  0.72680506 0.66465548 0.23298294 0.80209965]
 [0.77608006 0.46045573 0.12207204 0.42534    0.23032179 0.18999618
  0.22563234 0.34865357 0.32539854 0.57913262]
 [0.98430982 0.71643607 0.59840655 0.64921321 0.59022802 0.34113225
  0.4675585  0.44427272 0.35379649 0.61130181]
 [0.11833824 0.16986547 0.43726055 0.84503995 0.62725326 0.16460904
  0.85433894 0.55308585 0.41863332 0.2316825 ]
 [0.87399825 0.02240478 0.39981169 0.03371879 0.51904283 0.10059763
  0.19658252 0.14832862 0.30071752 0.96622772]
 [0.56635343 0.70919577 0.78782767 0.56725197 0.116808   0.87150207
  0.91632521 0.32346037 0.02504827 0.79642608]
 [0.90709212 0.91544483 0.82558081 0.41661579 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
vect=np.random.random(30)
mean_value=np.mean(vect)
print(f"vector of size 30 :\n{vect}")
print(f"mean_value :{mean_value}")

vector of size 30 :
[0.3533508  0.51518199 0.00455172 0.82983458 0.11505048 0.11258119
 0.31887759 0.20706008 0.33312716 0.52020779 0.60073915 0.17356573
 0.40605847 0.15695535 0.87155582 0.14309798 0.03543653 0.51149871
 0.03324114 0.18016751 0.36975194 0.39737577 0.89053736 0.34068332
 0.20003477 0.96530718 0.24547483 0.06066949 0.45783896 0.96175529]
mean_value :0.37705228838691013


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
arr = np.array([[1 if i == 0 or i == 4 or j == 0 or j == 4 else 0 for j in range(5)] for i in range(5)])
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
original_arr= np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

bordered_arr = np.pad(original_arr, pad_width=1, mode='constant', constant_values=0)
bordered_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [37]:

original_arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

rows, cols = original_arr.shape
bordered_arr = np.zeros((rows + 2, cols + 2), dtype=original_arr.dtype)
bordered_arr[1:-1, 1:-1] = original_arr

bordered_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [82]:
result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.3 == 3 * 0.1

print("0 * np.nan:", result1)
print("np.nan == np.nan:", result2)
print("np.inf > np.nan:", result3)
print("np.nan - np.nan:", result4)
print("np.nan in set([np.nan]):", result5)
print("0.3 == 3 * 0.1:", result6)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [46]:
matrix = np.array([[i  if j == i-1  else 0 for j in range(5)] for i in range(5)])

matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [47]:
checkerboard = np.array([[((i + j) % 2) for j in range(8)] for i in range(8)])
checkerboard 

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 21. Create a checkerboard 8x8 matrix using the tile function (search on it )

In [49]:

pattern = np.array([[0, 1],
                    [1, 0]])

checkerboard= np.tile(pattern, (4, 4))
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix knowing normalization = (x-min/max-min )

In [50]:
matrix = np.random.rand(5, 5)
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(f"matrix :\n{matrix}")
print(f"normalized_matrix :\n{normalized_matrix}")

matrix :
[[0.73028524 0.56705595 0.87410029 0.01306761 0.8074333 ]
 [0.5649348  0.16653484 0.2481348  0.61340062 0.3276072 ]
 [0.9464845  0.42135434 0.13381189 0.48860504 0.47954631]
 [0.68943108 0.05268454 0.48998135 0.57211529 0.75125051]
 [0.79956566 0.90032466 0.21054986 0.0064486  0.01073808]]
normalized_matrix :
[[0.77000958 0.59636803 0.92299846 0.00704123 0.85207885]
 [0.59411157 0.17029801 0.25710316 0.64566898 0.34164504]
 [1.         0.44137223 0.13548769 0.5129128  0.50327621]
 [0.72654936 0.04918529 0.5143769  0.6017501  0.7923122 ]
 [0.84370934 0.95089567 0.21712071 0.         0.00456311]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]])


matrix2 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])


result = np.dot(matrix1, matrix2)
result

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [54]:
arr = np.array([1, 4, 7, 2, 5, 8, 3, 6])

arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 1, -4, -7,  2, -5,  8,  3, -6])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [80]:
# Expression 1: np.array(0) / np.array(0)
try:
    result1 = np.array(0) / np.array(0)
except Exception as e:
    result1 = e
print("np.array(0) / np.array(0):", result1)

# Expression 2: np.array(0) // np.array(0)
try:
    result2 = np.array(0) // np.array(0)
except Exception as e:
    result2 = e
print("np.array(0) // np.array(0):", result2)

# Expression 3: np.array([np.nan]).astype(int).astype(float)
try:
    result3 = np.array([np.nan]).astype(int).astype(float)
except Exception as e:
    result3 = e
print("np.array([np.nan]).astype(int).astype(float):", result3)

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [-2.14748365e+09]


C:\Users\user\AppData\Local\Temp\ipykernel_26404\8105288.py:3: RuntimeWarning: invalid value encountered in true_divide
  result1 = np.array(0) / np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_26404\8105288.py:10: RuntimeWarning: divide by zero encountered in floor_divide
  result2 = np.array(0) // np.array(0)


#### 30. How to find common values between two arrays? (★☆☆)

In [58]:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 3, 8])

common_values = np.intersect1d(arr1, arr2)
common_values 

array([3, 4, 5])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [81]:
result1 = np.sqrt(-1)
result2 = np.emath.sqrt(-1)

print("np.sqrt(-1):", result1)
print("np.emath.sqrt(-1):", result2)
print("np.sqrt(-1) == np.emath.sqrt(-1):", result1 == result2)

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j
np.sqrt(-1) == np.emath.sqrt(-1): False


C:\Users\user\AppData\Local\Temp\ipykernel_26404\525491203.py:1: RuntimeWarning: invalid value encountered in sqrt
  result1 = np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [60]:

today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2024-08-08
Today's date: 2024-08-09
Tomorrow's date: 2024-08-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [61]:

start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')  

dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(f"Dates in July 2016:\n{dates}")

Dates in July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [62]:
import numpy as np

A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

temp = A + B

neg_half_A = -A / 2

result = temp * neg_half_A

print(f"Result:\n{result}")



Result:
[ -3.  -8. -15. -24.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [63]:

random_array = np.random.rand(5) * 10  

print("Original Array:")
print(random_array)

# Method 1
int_part1 = random_array.astype(int)
print("Method 1 (astype):")
print(int_part1)

# Method 2
int_part2 = np.floor(random_array).astype(int)
print("Method 2 (np.floor):")
print(int_part2)

# Method 3
int_part3 = np.trunc(random_array).astype(int)
print("Method 3 (np.trunc):")
print(int_part3)

# Method 4
int_part4 = random_array // 1
print("Method 4 (integer division):")
print(int_part4)


Original Array:
[7.35799702 8.57997445 6.49369098 3.67253389 5.5682013 ]
Method 1 (astype):
[7 8 6 3 5]
Method 2 (np.floor):
[7 8 6 3 5]
Method 3 (np.trunc):
[7 8 6 3 5]
Method 4 (integer division):
[7. 8. 6. 3. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
matrix = np.tile(np.arange(5), (5, 1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [66]:
def int_generator():
    for i in range(10):
        yield i

gen = int_generator()

arr = np.fromiter(gen, dtype=int)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [67]:
vector = np.linspace(0, 1, 12)[1:-1]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [68]:

vector = np.random.rand(10)

sorted_vector = np.sort(vector)

print("Random vector:", vector)
print("Sorted vector:", sorted_vector)

Random vector: [0.41645151 0.51247694 0.1007573  0.04590142 0.54834343 0.97163601
 0.36798047 0.65329486 0.11049441 0.75796388]
Sorted vector: [0.04590142 0.1007573  0.11049441 0.36798047 0.41645151 0.51247694
 0.54834343 0.65329486 0.75796388 0.97163601]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [70]:
array = np.array([1, 2, 3, 4, 5])
total = sum(array)
total

15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [73]:
A = np.random.rand(3, 3) 
B = np.random.rand(3, 3)
are_equal = np.array_equal(A, B)

print("Arrays are equal:", are_equal)

Arrays are equal: False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [75]:

vector = np.random.rand(10)

max_index = np.argmax(vector)

vector[max_index] = 0

print("Modified vector:", vector)


Modified vector: [0.0698249  0.38849528 0.38163634 0.         0.58323866 0.73164892
 0.20639186 0.73036942 0.64751331 0.78376137]


#### 49. How to print all the values of an array? (★★☆)

In [85]:

arr = np.arange(100)

np.set_printoptions(threshold=np.inf)

print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [86]:

vector = np.array([1, 5, 80, 12, 15])
scalar = 70

closest_value = vector[np.abs(vector - scalar).argmin()]

closest_value


80