# 1- Create a NumPy program to create a 3x3 identity matrix

In [1]:
import numpy as np
identity_matrix = np.array([[1 if i == j else 0 for j in range(3)] for i in range(3)])
print(f"3x3 Identity Matrix:\n{identity_matrix}")

3x3 Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# 2- Create a NumPy program to generate 5 random number between 0 and 1


In [2]:
import numpy as np
numbers = np.random.rand(5)
print(f"5 Random Numbers between 0 and 1: {numbers}")

5 Random Numbers between 0 and 1: [0.98686873 0.97003974 0.49728216 0.31395501 0.05087008]


# 3- Write a NumPy program to append values to the end of an array.
	Expected Output:
	Original array:
	[10, 20, 30]
	After append values to the end of the array:
	[10 20 30 40 50 60 70 80 90]



In [3]:
import numpy as np
original_array = np.array([10, 20, 30])
values_to_append = np.array([40, 50, 60, 70, 80, 90])

result_array = np.append(original_array, values_to_append)

print(f"Original array:\n{original_array}")
print(f"After appending values to the end of the array:\n{result_array}")


Original array:
[10 20 30]
After appending values to the end of the array:
[10 20 30 40 50 60 70 80 90]


# 4- Write a NumPy program to create a 3X4 array and iterate over it using nditer.


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("Iterating over the 3x4 array:")
for element in np.nditer(arr):
    print(element, end=' ')


Iterating over the 3x4 array:
1 2 3 4 5 6 7 8 9 10 11 12 

# 5- Write a NumPy program to create a 1-D array then convert it into 2-D array then print value and position for each value using ndenumerate.



In [6]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_2d = arr_1d.reshape((2, 5))

for index, value in np.ndenumerate(arr_2d):
    print(f"Position: {index}, Value: {value}")


Position: (0, 0), Value: 1
Position: (0, 1), Value: 2
Position: (0, 2), Value: 3
Position: (0, 3), Value: 4
Position: (0, 4), Value: 5
Position: (1, 0), Value: 6
Position: (1, 1), Value: 7
Position: (1, 2), Value: 8
Position: (1, 3), Value: 9
Position: (1, 4), Value: 10
